apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: advanced-inference-pool
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: inference-gateway
  targetPorts:
  - number: 8000
  endpointPickerRef:
    group: ""
    kind: Service
    name: inference-gateway-svc
    port:
      number: 8080
