apiVersion: v1
kind: Service
metadata:
  name: inference-gateway-svc
  namespace: ${NAMESPACE}
  labels:
    app: inference-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: epp
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: vllm
  selector:
    app: inference-gateway
  type: ClusterIP
